### ISSUE TITLE
thread 'main' panicked at 'cannot transmute_copy if U is larger than T', /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\mem\mod.rs:1057:5

### ISSUE THREAD

**Issue by ykong1337** [autopilot-rs/autopilot-rs#46]
```
thread 'main' panicked at 'cannot transmute_copy if U is larger than T', /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\mem\mod.rs:1057:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:142
   2: core::mem::transmute_copy<winapi::um::winuser::KEYBDINPUT,winapi::um::winuser::INPUT_u>
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\mem\mod.rs:1057
   3: autopilot::key::system_toggle<autopilot::key::Character>
             at C:\Users\root\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\autopilot-0.4.0\src\key.rs:486
   4: autopilot::key::toggle<autopilot::key::Character>
             at C:\Users\root\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\autopilot-0.4.0\src\key.rs:164
   5: autopilot::key::tap<autopilot::key::Character>
             at C:\Users\root\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\autopilot-0.4.0\src\key.rs:146
   6: demo::main
             at .\src\demo.rs:23
   7: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\demo.exe` (exit code: 101)

Process finished with exit code 101
```

**Comment by Ykong1337** [comment]
rust version v1.65.0
